version: "3"

services:
  relearn_mongo:
    container_name: relearn_mongo
    image: mongo:latest
    env_file: .env
    volumes:
      - ./.data/mongodbdata:/data/db
    command: mongod --auth
    ports:
      - 27018:27017
    networks:
      - api-network
  relearn_api:
    container_name: relearn_api
    build:
      context: .
    volumes:
      - .:/usr/src/app
    env_file: .env
    depends_on:
      - relearn_mongo
    networks:
      - api-network
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./.conf/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - relearn_api
    networks:
      - api-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --email jurakulek@gmail.com --agree-tos --no-eff-email --staging -d example.com -d 161.35.205.186

volumes:
  certbot-etc:
  certbot-var:


networks:
  api-network:
    driver: bridge